name: Package
on: [push, pull_request]

jobs:
  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller pyqt5==5.15.6 lxml
      - name: Build LabelImg
        run: |
          pyrcc5 -o libs/resources.py resources.qrc
      - name: Package LabelImg
        run: |
          Remove-Item -Recurse -Force dist, build -ErrorAction SilentlyContinue
          pyinstaller labelimg.spec
      - name: Archive Windows build
        run: |
          Compress-Archive -Path dist\labelimg\* -DestinationPath dist\labelImg-windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Windows artifact
          path: dist/labelImg-windows.zip
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller pyqt5==5.15.6 lxml
      - name: Build LabelImg
        run: |
          pyrcc5 -o libs/resources.py resources.qrc
      - name: Package LabelImg
        run: |
          rm -rf dist build
          pyinstaller labelimg.spec
      - name: Archive Linux build
        run: |
          cd dist
          tar czf labelImg-linux.tgz labelimg
      - uses: actions/upload-artifact@v4
        with:
          name: Linux artifact
          path: dist/labelImg-linux.tgz
